name: Handle Hanoi Move

on:
  issues:
    types: [opened]

jobs:
  process_move:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Run Python script to process move
        run: |
          python3 hanoi_move.py "${{ github.event.issue.title }}"

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v7
        with:
          author_name: "GitHub Actions"
          author_email: "action@github.com"
          message: "Updated Hanoi game state"
